export interface Campaign {
  id: string // We'll keep this as string for mock data though DB uses SERIAL
  user_id: number
  campaign_logo: string
  entrepreneur_name: string
  campaign_name: string
  campaign_description: string
  about_project: string
  campaign_summary: string
  goal_coverage_subject: string
  entrepreneur_stage_id: number
  location: string
  category: string
  business_models_id: number
  sector: string
  entrepreneurs_mails: string
  is_past_campaign: boolean
  campaign_status: string
  created_at: string // We'll use string for dates in mock data
  updated_at: string
  // Additional fields needed for UI that aren't in DB schema
  currentAmount: number
  goalAmount: number
  daysLeft: number
  teamSize: number
  technology: string
  companyName: string
  imageUrl: string
  startDate: string
  endDate: string
  funding: Funding
  market_analysis?: string
  competition_analysis?: string
  target_audience?: string
  swot?: {
    strengths: string[]
    weaknesses: string[]
    opportunities: string[]
    threats: string[]
  }
  strategies?: string
  businessPlan?: string
  investorPresentation?: string
  risks?: string
}

export interface UpcomingCampaign {
  id: string
  title: string
  description: string
  imageUrl: string
  expectedLaunchDate: string
}

export interface SuccessfulCampaign {
  id: string
  title: string
  description: string
  imageUrl: string
  raisedAmount: number
  completionDate: string
}

export interface Partner {
  id: string
  name: string
  logoUrl: string
}

export interface Subsidiary {
  id: string
  name: string
  description: string
  logoUrl: string
}

export interface Funding {
  need_amount_fund: number
  amount_given_share?: number
  number_sale_share?: number
  post_funding_capital?: number
  sales_share_price?: number
  sales_nominal_share_price?: number
}

export const allCampaigns: Campaign[] = [
  {
    id: "1",
    user_id: 1,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ahmet Yılmaz",
    campaign_name: "Yenilenebilir Enerji Projesi",
    campaign_description: "Güneş enerjisi ile çalışan akıllı şehir sistemleri geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Enerji verimliliği",
    entrepreneur_stage_id: 1,
    location: "İstanbul",
    category: "Enerji",
    business_models_id: 1,
    sector: "Yenilenebilir Enerji",
    entrepreneurs_mails: "ahmet@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-30T00:00:00Z",
    // UI specific fields
    currentAmount: 350000,
    goalAmount: 500000,
    daysLeft: 15,
    teamSize: 5,
    technology: "İleri AI ve IoT Sensörleri",
    companyName: "ARD Enerji",
    imageUrl: "/placeholder.svg",
    startDate: "1 Ocak 2024",
    endDate: "1 Haziran 2024",
    funding: {
      need_amount_fund: 500000,
      amount_given_share: 100000,
      number_sale_share: 1000,
      post_funding_capital: 2000000,
      sales_share_price: 500,
      sales_nominal_share_price: 100,
    },
    swot: {
      strengths: ["Yenilikçi teknoloji", "Güçlü Ar-Ge ekibi", "Geniş pazar potansiyeli"],
      weaknesses: ["Sınırlı finansal kaynaklar", "Marka bilinirliği eksikliği"],
      opportunities: ["Artan çevre bilinci", "Devlet teşvikleri", "Uluslararası pazar fırsatları"],
      threats: ["Hızlı teknolojik değişimler", "Güçlü rakipler", "Ekonomik belirsizlikler"],
    },
    strategies:
      "Şirketimiz, yenilikçi teknolojimizi kullanarak enerji verimliliği pazarında lider konuma gelmeyi hedeflemektedir. Bunu yaparken, Ar-Ge yatırımlarımızı artırarak ürün yelpazemizi genişletmeyi ve uluslararası pazarlara açılmayı planlıyoruz.",
    businessPlan:
      "İş planımız, ilk yıl içinde prototip geliştirme ve test aşamalarını tamamlayıp, ikinci yılda ürünümüzü piyasaya sürmeyi öngörmektedir. Üçüncü yılda ise uluslararası pazarlara açılmayı hedefliyoruz.",
    investorPresentation:
      "Yatırımcı sunumumuz, projemizin detaylı finansal projeksiyonlarını, pazar analizini ve büyüme stratejilerimizi içermektedir. Sunumda ayrıca ekibimizin uzmanlıkları ve başarı geçmişleri de yer almaktadır.",
    risks:
      "Projemizin başlıca riskleri arasında teknolojik gelişmelerin hızı, pazar kabulü ve finansman bulma zorlukları yer almaktadır. Bu riskleri minimize etmek için sürekli Ar-Ge çalışmaları yapıyor ve pazar trendlerini yakından takip ediyoruz.",
  },
  {
    id: "2",
    user_id: 2,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ayşe Kaya",
    campaign_name: "Biyoteknoloji Girişimi",
    campaign_description: "Yapay organ üretimi için yenilikçi teknoloji geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Sağlık teknolojileri",
    entrepreneur_stage_id: 2,
    location: "Ankara",
    category: "Sağlık",
    business_models_id: 2,
    sector: "Biyoteknoloji",
    entrepreneurs_mails: "ayse@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-02-15T00:00:00Z",
    updated_at: "2024-02-28T00:00:00Z",
    currentAmount: 500000,
    goalAmount: 750000,
    daysLeft: 20,
    teamSize: 8,
    technology: "Biyomühendislik ve 3D Biyobasım",
    companyName: "ARD Sağlık",
    imageUrl: "/placeholder.svg",
    startDate: "15 Şubat 2024",
    endDate: "15 Ağustos 2024",
    funding: {
      need_amount_fund: 750000,
      amount_given_share: 150000,
      number_sale_share: 1500,
      post_funding_capital: 3000000,
      sales_share_price: 750,
      sales_nominal_share_price: 150,
    },
  },
  {
    id: "3",
    user_id: 3,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Mehmet Öz",
    campaign_name: "Eğitim Teknolojileri Platformu",
    campaign_description: "Yapay zeka destekli kişiselleştirilmiş öğrenme deneyimi sunuyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Eğitim teknolojileri",
    entrepreneur_stage_id: 3,
    location: "İzmir",
    category: "Eğitim",
    business_models_id: 3,
    sector: "Eğitim Teknolojileri",
    entrepreneurs_mails: "mehmet@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-15T00:00:00Z",
    currentAmount: 200000,
    goalAmount: 300000,
    daysLeft: 10,
    teamSize: 6,
    technology: "Makine Öğrenimi ve Veri Analitiği",
    companyName: "ARD Bilişim",
    imageUrl: "/placeholder.svg",
    startDate: "1 Mart 2024",
    endDate: "1 Eylül 2024",
    funding: {
      need_amount_fund: 300000,
      amount_given_share: 60000,
      number_sale_share: 600,
      post_funding_capital: 1200000,
      sales_share_price: 300,
      sales_nominal_share_price: 60,
    },
  },
  {
    id: "4",
    user_id: 4,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Fatma Demir",
    campaign_name: "Sürdürülebilir Tarım Projesi",
    campaign_description: "Akıllı sulama sistemleri ve verimli toprak yönetimi çözümleri.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Sürdürülebilir tarım",
    entrepreneur_stage_id: 1,
    location: "Bursa",
    category: "Tarım",
    business_models_id: 1,
    sector: "Sürdürülebilir Tarım",
    entrepreneurs_mails: "fatma@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-15T00:00:00Z",
    currentAmount: 150000,
    goalAmount: 400000,
    daysLeft: 25,
    teamSize: 4,
    technology: "Sensörler ve Veri Analitiği",
    companyName: "ARD Tarım",
    imageUrl: "/placeholder.svg",
    startDate: "1 Nisan 2024",
    endDate: "1 Ekim 2024",
    funding: {
      need_amount_fund: 400000,
      amount_given_share: 80000,
      number_sale_share: 800,
      post_funding_capital: 1600000,
      sales_share_price: 400,
      sales_nominal_share_price: 80,
    },
  },
  {
    id: "5",
    user_id: 5,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ali Can",
    campaign_name: "Temiz Okyanus Girişimi",
    campaign_description: "Okyanus temizleme ve plastik geri dönüşüm teknolojileri geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Çevre koruma",
    entrepreneur_stage_id: 2,
    location: "Antalya",
    category: "Çevre",
    business_models_id: 2,
    sector: "Çevre Teknolojileri",
    entrepreneurs_mails: "ali@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-05-15T00:00:00Z",
    currentAmount: 300000,
    goalAmount: 600000,
    daysLeft: 30,
    teamSize: 7,
    technology: "Robotik ve Yapay Zeka",
    companyName: "ARD Çevre",
    imageUrl: "/placeholder.svg",
    startDate: "1 Mayıs 2024",
    endDate: "1 Kasım 2024",
    funding: {
      need_amount_fund: 600000,
      amount_given_share: 120000,
      number_sale_share: 1200,
      post_funding_capital: 2400000,
      sales_share_price: 600,
      sales_nominal_share_price: 120,
    },
  },
  {
    id: "6",
    user_id: 6,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Zeynep Gül",
    campaign_name: "Akıllı Ulaşım Çözümleri",
    campaign_description: "Trafik optimizasyonu ve elektrikli araç şarj istasyonları ağı kuruyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Ulaşım teknolojileri",
    entrepreneur_stage_id: 3,
    location: "İstanbul",
    category: "Ulaşım",
    business_models_id: 3,
    sector: "Akıllı Ulaşım",
    entrepreneurs_mails: "zeynep@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2024-06-15T00:00:00Z",
    currentAmount: 450000,
    goalAmount: 800000,
    daysLeft: 18,
    teamSize: 9,
    technology: "Yapay Zeka ve IoT",
    companyName: "ARD Ulaşım",
    imageUrl: "/placeholder.svg",
    startDate: "1 Haziran 2024",
    endDate: "1 Aralık 2024",
    funding: {
      need_amount_fund: 800000,
      amount_given_share: 160000,
      number_sale_share: 1600,
      post_funding_capital: 3200000,
      sales_share_price: 800,
      sales_nominal_share_price: 160,
    },
  },
  {
    id: "7",
    user_id: 7,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Veli Bayram",
    campaign_name: "Yapay Zeka Destekli Sağlık Asistanı",
    campaign_description: "Kişiselleştirilmiş tıbbi tanı ve tedavi önerileri sunan AI platformu.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Sağlık teknolojileri",
    entrepreneur_stage_id: 1,
    location: "Ankara",
    category: "Sağlık",
    business_models_id: 1,
    sector: "Sağlık Teknolojileri",
    entrepreneurs_mails: "veli@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-07-01T00:00:00Z",
    updated_at: "2024-07-15T00:00:00Z",
    currentAmount: 700000,
    goalAmount: 1000000,
    daysLeft: 12,
    teamSize: 10,
    technology: "Derin Öğrenme ve Büyük Veri",
    companyName: "ARD Sağlık",
    imageUrl: "/placeholder.svg",
    startDate: "1 Temmuz 2024",
    endDate: "1 Ocak 2025",
    funding: {
      need_amount_fund: 1000000,
      amount_given_share: 200000,
      number_sale_share: 2000,
      post_funding_capital: 4000000,
      sales_share_price: 1000,
      sales_nominal_share_price: 200,
    },
  },
  {
    id: "8",
    user_id: 8,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ayşe Yılmaz",
    campaign_name: "Uzay Madenciliği Araştırma Projesi",
    campaign_description: "Asteroidlerden değerli maden çıkarma teknolojileri geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Uzay teknolojileri",
    entrepreneur_stage_id: 2,
    location: "İstanbul",
    category: "Uzay",
    business_models_id: 2,
    sector: "Uzay Madenciliği",
    entrepreneurs_mails: "ayseyilmaz@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-08-01T00:00:00Z",
    updated_at: "2024-08-15T00:00:00Z",
    currentAmount: 1200000,
    goalAmount: 2000000,
    daysLeft: 40,
    teamSize: 12,
    technology: "Robotik ve Uzay Teknolojileri",
    companyName: "ARD Uzay",
    imageUrl: "/placeholder.svg",
    startDate: "1 Ağustos 2024",
    endDate: "1 Şubat 2025",
    funding: {
      need_amount_fund: 2000000,
      amount_given_share: 400000,
      number_sale_share: 4000,
      post_funding_capital: 8000000,
      sales_share_price: 2000,
      sales_nominal_share_price: 400,
    },
  },
  {
    id: "9",
    user_id: 9,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Mehmet Demir",
    campaign_name: "Biyoçeşitlilik Koruma İnisiyatifi",
    campaign_description: "Nesli tükenmekte olan türleri koruma ve habitat restorasyon projesi.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Çevre koruma",
    entrepreneur_stage_id: 3,
    location: "Ankara",
    category: "Çevre",
    business_models_id: 3,
    sector: "Çevre Koruma",
    entrepreneurs_mails: "mehmetdemir@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2024-09-15T00:00:00Z",
    currentAmount: 180000,
    goalAmount: 350000,
    daysLeft: 22,
    teamSize: 3,
    technology: "Veri Analitiği ve Çevresel Modelleme",
    companyName: "ARD Çevre",
    imageUrl: "/placeholder.svg",
    startDate: "1 Eylül 2024",
    endDate: "1 Mart 2025",
    funding: {
      need_amount_fund: 350000,
      amount_given_share: 70000,
      number_sale_share: 700,
      post_funding_capital: 1400000,
      sales_share_price: 350,
      sales_nominal_share_price: 70,
    },
  },
  {
    id: "10",
    user_id: 10,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Fatma Can",
    campaign_name: "Akıllı Ev Otomasyon Sistemleri",
    campaign_description: "Enerji tasarruflu ve kullanıcı dostu akıllı ev çözümleri geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Ev otomasyonu",
    entrepreneur_stage_id: 1,
    location: "İzmir",
    category: "Teknoloji",
    business_models_id: 1,
    sector: "Ev Otomasyonu",
    entrepreneurs_mails: "fatmacan@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-09-15T00:00:00Z",
    updated_at: "2024-09-29T00:00:00Z",
    currentAmount: 280000,
    goalAmount: 450000,
    daysLeft: 28,
    teamSize: 6,
    technology: "IoT ve Mobil Uygulamalar",
    companyName: "ARD Teknoloji",
    imageUrl: "/placeholder.svg",
    startDate: "15 Eylül 2024",
    endDate: "15 Mart 2025",
    funding: {
      need_amount_fund: 450000,
      amount_given_share: 90000,
      number_sale_share: 900,
      post_funding_capital: 1800000,
      sales_share_price: 450,
      sales_nominal_share_price: 90,
    },
  },
  {
    id: "11",
    user_id: 11,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ali Gül",
    campaign_name: "Dijital Sanat Platformu",
    campaign_description: "Sanatçılar için blockchain tabanlı NFT pazaryeri oluşturuyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Dijital sanat",
    entrepreneur_stage_id: 2,
    location: "İstanbul",
    category: "Sanat",
    business_models_id: 2,
    sector: "Dijital Sanat",
    entrepreneurs_mails: "aligul@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-10-01T00:00:00Z",
    updated_at: "2024-10-15T00:00:00Z",
    currentAmount: 320000,
    goalAmount: 550000,
    daysLeft: 35,
    teamSize: 8,
    technology: "Blockchain ve Web3",
    companyName: "ARD Dijital",
    imageUrl: "/placeholder.svg",
    startDate: "1 Ekim 2024",
    endDate: "1 Nisan 2025",
    funding: {
      need_amount_fund: 550000,
      amount_given_share: 110000,
      number_sale_share: 1100,
      post_funding_capital: 2200000,
      sales_share_price: 550,
      sales_nominal_share_price: 110,
    },
  },
  {
    id: "12",
    user_id: 12,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Zeynep Bayram",
    campaign_name: "Gıda Güvenliği Takip Sistemi",
    campaign_description: "Tarımdan sofraya gıda güvenliğini sağlayan blockchain çözümü.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Gıda güvenliği",
    entrepreneur_stage_id: 3,
    location: "Ankara",
    category: "Gıda",
    business_models_id: 3,
    sector: "Gıda Teknolojileri",
    entrepreneurs_mails: "zeynepbayram@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-10-15T00:00:00Z",
    updated_at: "2024-10-29T00:00:00Z",
    currentAmount: 420000,
    goalAmount: 700000,
    daysLeft: 19,
    teamSize: 7,
    technology: "Blockchain ve IoT Sensörleri",
    companyName: "ARD Gıda",
    imageUrl: "/placeholder.svg",
    startDate: "15 Ekim 2024",
    endDate: "15 Nisan 2025",
    funding: {
      need_amount_fund: 700000,
      amount_given_share: 140000,
      number_sale_share: 1400,
      post_funding_capital: 2800000,
      sales_share_price: 700,
      sales_nominal_share_price: 140,
    },
  },
  {
    id: "13",
    user_id: 13,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Veli Yılmaz",
    campaign_name: "Yapay Zeka Destekli Hukuk Asistanı",
    campaign_description: "Hukuki süreçleri otomatikleştiren ve analiz eden AI platformu.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Hukuk teknolojileri",
    entrepreneur_stage_id: 1,
    location: "İstanbul",
    category: "Hukuk",
    business_models_id: 1,
    sector: "Hukuk Teknolojileri",
    entrepreneurs_mails: "veliyilmaz@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-11-01T00:00:00Z",
    updated_at: "2024-11-15T00:00:00Z",
    currentAmount: 350000,
    goalAmount: 600000,
    daysLeft: 24,
    teamSize: 5,
    technology: "Doğal Dil İşleme ve Makine Öğrenimi",
    companyName: "ARD Hukuk",
    imageUrl: "/placeholder.svg",
    startDate: "1 Kasım 2024",
    endDate: "1 Mayıs 2025",
    funding: {
      need_amount_fund: 600000,
      amount_given_share: 120000,
      number_sale_share: 1200,
      post_funding_capital: 2400000,
      sales_share_price: 600,
      sales_nominal_share_price: 120,
    },
  },
  {
    id: "14",
    user_id: 14,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ayşe Can",
    campaign_name: "Sanal Gerçeklik Eğitim Platformu",
    campaign_description: "Endüstriyel eğitimler için immersif VR deneyimleri sunuyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Eğitim teknolojileri",
    entrepreneur_stage_id: 2,
    location: "Ankara",
    category: "Eğitim",
    business_models_id: 2,
    sector: "Eğitim Teknolojileri",
    entrepreneurs_mails: "aysecan@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-11-15T00:00:00Z",
    updated_at: "2024-11-29T00:00:00Z",
    currentAmount: 580000,
    goalAmount: 850000,
    daysLeft: 16,
    teamSize: 9,
    technology: "VR/AR ve 3D Modelleme",
    companyName: "ARD Eğitim",
    imageUrl: "/placeholder.svg",
    startDate: "15 Kasım 2024",
    endDate: "15 Mayıs 2025",
    funding: {
      need_amount_fund: 850000,
      amount_given_share: 170000,
      number_sale_share: 1700,
      post_funding_capital: 3400000,
      sales_share_price: 850,
      sales_nominal_share_price: 170,
    },
  },
  {
    id: "15",
    user_id: 15,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Mehmet Gül",
    campaign_name: "Akıllı Şehir Atık Yönetimi",
    campaign_description: "IoT sensörleri ile optimize edilmiş şehir atık toplama sistemi.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Atık yönetimi",
    entrepreneur_stage_id: 3,
    location: "İzmir",
    category: "Çevre",
    business_models_id: 3,
    sector: "Çevre Teknolojileri",
    entrepreneurs_mails: "mehmetgul@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-12-01T00:00:00Z",
    updated_at: "2024-12-15T00:00:00Z",
    currentAmount: 480000,
    goalAmount: 750000,
    daysLeft: 21,
    teamSize: 6,
    technology: "IoT ve Büyük Veri Analizi",
    companyName: "ARD Çevre",
    imageUrl: "/placeholder.svg",
    startDate: "1 Aralık 2024",
    endDate: "1 Haziran 2025",
    funding: {
      need_amount_fund: 750000,
      amount_given_share: 150000,
      number_sale_share: 1500,
      post_funding_capital: 3000000,
      sales_share_price: 750,
      sales_nominal_share_price: 150,
    },
  },
  {
    id: "16",
    user_id: 16,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Fatma Bayram",
    campaign_name: "Drone ile Ağaçlandırma Projesi",
    campaign_description: "Otonom dronlar kullanarak geniş alanları hızlıca ağaçlandırıyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Ormancılık",
    entrepreneur_stage_id: 1,
    location: "Bursa",
    category: "Çevre",
    business_models_id: 1,
    sector: "Ormancılık",
    entrepreneurs_mails: "fatmabayram@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2024-12-15T00:00:00Z",
    updated_at: "2024-12-29T00:00:00Z",
    currentAmount: 620000,
    goalAmount: 900000,
    daysLeft: 14,
    teamSize: 8,
    technology: "Drone Teknolojisi ve AI",
    companyName: "ARD Orman",
    imageUrl: "/placeholder.svg",
    startDate: "15 Aralık 2024",
    endDate: "15 Haziran 2025",
    funding: {
      need_amount_fund: 900000,
      amount_given_share: 180000,
      number_sale_share: 1800,
      post_funding_capital: 3600000,
      sales_share_price: 900,
      sales_nominal_share_price: 180,
    },
  },
  {
    id: "17",
    user_id: 17,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ali Yılmaz",
    campaign_name: "Kişiselleştirilmiş Beslenme AI",
    campaign_description: "Genetik ve yaşam tarzına göre özelleştirilmiş beslenme planları sunan AI.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Sağlık teknolojileri",
    entrepreneur_stage_id: 2,
    location: "İstanbul",
    category: "Sağlık",
    business_models_id: 2,
    sector: "Sağlık Teknolojileri",
    entrepreneurs_mails: "aliyilmaz@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-15T00:00:00Z",
    currentAmount: 310000,
    goalAmount: 550000,
    daysLeft: 32,
    teamSize: 7,
    technology: "AI ve Genetik Analiz",
    companyName: "ARD Sağlık",
    imageUrl: "/placeholder.svg",
    startDate: "1 Ocak 2025",
    endDate: "1 Temmuz 2025",
    funding: {
      need_amount_fund: 550000,
      amount_given_share: 110000,
      number_sale_share: 1100,
      post_funding_capital: 2200000,
      sales_share_price: 550,
      sales_nominal_share_price: 110,
    },
  },
  {
    id: "18",
    user_id: 18,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Zeynep Can",
    campaign_name: "Mikroplastik Temizleme Teknolojisi",
    campaign_description: "Okyanuslardaki mikroplastikleri temizleyen nano-robot teknolojisi.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Çevre koruma",
    entrepreneur_stage_id: 3,
    location: "Ankara",
    category: "Çevre",
    business_models_id: 3,
    sector: "Çevre Teknolojileri",
    entrepreneurs_mails: "zeynepcan@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2025-01-15T00:00:00Z",
    updated_at: "2025-01-29T00:00:00Z",
    currentAmount: 780000,
    goalAmount: 1200000,
    daysLeft: 26,
    teamSize: 10,
    technology: "Nano-robotik ve Çevre Mühendisliği",
    companyName: "ARD Okyanus",
    imageUrl: "/placeholder.svg",
    startDate: "15 Ocak 2025",
    endDate: "15 Temmuz 2025",
    funding: {
      need_amount_fund: 1200000,
      amount_given_share: 240000,
      number_sale_share: 2400,
      post_funding_capital: 4800000,
      sales_share_price: 1200,
      sales_nominal_share_price: 240,
    },
  },
  {
    id: "19",
    user_id: 19,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Veli Gül",
    campaign_name: "Quantum Bilgisayar Araştırma Projesi",
    campaign_description: "Quantum bilgisayarların pratik uygulamalarını geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Teknoloji",
    entrepreneur_stage_id: 1,
    location: "İstanbul",
    category: "Teknoloji",
    business_models_id: 1,
    sector: "Quantum Bilgisayarlar",
    entrepreneurs_mails: "veligul@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2025-02-01T00:00:00Z",
    updated_at: "2025-02-15T00:00:00Z",
    currentAmount: 1500000,
    goalAmount: 2500000,
    daysLeft: 45,
    teamSize: 15,
    technology: "Quantum Hesaplama ve Kriptografi",
    companyName: "ARD Quantum",
    imageUrl: "/placeholder.svg",
    startDate: "1 Şubat 2025",
    endDate: "1 Ağustos 2025",
    funding: {
      need_amount_fund: 2500000,
      amount_given_share: 500000,
      number_sale_share: 5000,
      post_funding_capital: 10000000,
      sales_share_price: 2500,
      sales_nominal_share_price: 500,
    },
  },
  {
    id: "20",
    user_id: 20,
    campaign_logo: "/placeholder.svg",
    entrepreneur_name: "Ayşe Bayram",
    campaign_name: "Biyomimetik Yapay Zeka",
    campaign_description: "Doğadan ilham alan, sürdürülebilir AI çözümleri geliştiriyoruz.",
    about_project: "Detaylı proje açıklaması...",
    campaign_summary: "Kısa proje özeti",
    goal_coverage_subject: "Yapay zeka",
    entrepreneur_stage_id: 2,
    location: "Ankara",
    category: "Teknoloji",
    business_models_id: 2,
    sector: "Yapay Zeka",
    entrepreneurs_mails: "aysebayram@example.com",
    is_past_campaign: false,
    campaign_status: "active",
    created_at: "2025-02-15T00:00:00Z",
    updated_at: "2025-02-28T00:00:00Z",
    currentAmount: 520000,
    goalAmount: 800000,
    daysLeft: 30,
    teamSize: 8,
    technology: "Biyomimetik AI ve Sürdürülebilir Hesaplama",
    companyName: "ARD Biyoteknoloji",
    imageUrl: "/placeholder.svg",
    startDate: "15 Şubat 2025",
    endDate: "15 Ağustos 2025",
    funding: {
      need_amount_fund: 800000,
      amount_given_share: 160000,
      number_sale_share: 1600,
      post_funding_capital: 3200000,
      sales_share_price: 800,
      sales_nominal_share_price: 160,
    },
  },
]

export const featuredCampaigns = allCampaigns.slice(0, 3)

export const upcomingCampaigns: UpcomingCampaign[] = [
  {
    id: "uc1",
    title: "Akıllı Şehir Çözümleri",
    description: "Şehirleri daha yaşanabilir ve sürdürülebilir hale getiren IoT tabanlı çözümler",
    imageUrl: "/placeholder.svg",
    expectedLaunchDate: "1 Ağustos 2024",
  },
  {
    id: "uc2",
    title: "Biyoplastik Üretim Tesisi",
    description: "Çevre dostu, biyolojik olarak parçalanabilen plastik üretimi",
    imageUrl: "/placeholder.svg",
    expectedLaunchDate: "15 Eylül 2024",
  },
  {
    id: "uc3",
    title: "Yapay Zeka Destekli Tarım",
    description: "Tarımda verimliliği artırmak için AI ve drone teknolojileri",
    imageUrl: "/placeholder.svg",
    expectedLaunchDate: "1 Ekim 2024",
  },
]

export const successfulCampaigns: SuccessfulCampaign[] = [
  {
    id: "sc1",
    title: "Elektrikli Scooter Paylaşım Ağı",
    description: "Şehir içi ulaşımda çevre dostu alternatif",
    imageUrl: "/placeholder.svg",
    raisedAmount: 2000000,
    completionDate: "15 Mart 2024",
  },
  {
    id: "sc2",
    title: "Güneş Enerjili Şarj İstasyonları",
    description: "Yenilenebilir enerji ile elektrikli araç şarj ağı",
    imageUrl: "/placeholder.svg",
    raisedAmount: 1500000,
    completionDate: "1 Nisan 2024",
  },
  {
    id: "sc3",
    title: "Akıllı Geri Dönüşüm Sistemleri",
    description: "IoT tabanlı atık yönetimi ve geri dönüşüm çözümleri",
    imageUrl: "/placeholder.svg",
    raisedAmount: 1000000,
    completionDate: "20 Nisan 2024",
  },
]

export const partners: Partner[] = [
  {
    id: "p1",
    name: "TechInvest A.Ş.",
    logoUrl: "/placeholder.svg",
  },
  {
    id: "p2",
    name: "GreenFuture Holding",
    logoUrl: "/placeholder.svg",
  },
  {
    id: "p3",
    name: "InnoVentures Ltd.",
    logoUrl: "/placeholder.svg",
  },
  {
    id: "p4",
    name: "SmartCapital Yatırım",
    logoUrl: "/placeholder.svg",
  },
]

export const subsidiaries: Subsidiary[] = [
  {
    id: "bilisim",
    name: "ARD Bilişim",
    description: "Deloitte EMEA Fast 500 ve Turkey Fast 50 Winner! ARD Bilişim bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-M7nMOpwJstRMSJlp7U6ZCCdXXalqRK.png",
  },
  {
    id: "enerji",
    name: "ARD Enerji",
    description: "Çevreye duyarlı teknolojiler… ARD Enerji bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Du3iDwbNhrz54oB8ODX2iWxTfHtvxU.png",
  },
  {
    id: "saglik",
    name: "ARD Sağlık",
    description: "Sağlık alanında en ileri teknoloji. ARD Sağlık bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-QAgtdSGbP4NMFXUd1WZplQojV2C8c5.png",
  },
  {
    id: "insaat",
    name: "ARD İnşaat",
    description: "Geleceği inşa ediyoruz! ARD İnşaat bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-C1NaTZo9xumyN16FyLb7oeGeptp4kD.png",
  },
  {
    id: "savunma",
    name: "ARD Savunma",
    description: "En yeni teknoloji, en yüksek kalite! ARD Savunma bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-6UDGjADUrPtPLnCvaehPBdJhVt9CHo.png",
  },
  {
    id: "danismanlik",
    name: "ARD Danışmanlık",
    description: "Kurumunuzun Geleceğini Şansa Bırakmayın. ARD Danışmanlık bir ARD GRUP HOLDİNG AŞ. iştirakidir.",
    logoUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-AXUVmHgdtCnnWWE96U7I7u4B1eleDe.png",
  },
]

export const successClubCampaigns = [
  {
    id: "sc1",
    title: "Elektrikli Scooter Paylaşım Ağı",
    companyName: "EcoRide A.Ş.",
    logo: "/placeholder.svg",
    amount: 2000000,
  },
  {
    id: "sc2",
    title: "Güneş Enerjili Şarj İstasyonları",
    companyName: "SolarCharge Ltd.",
    logo: "/placeholder.svg",
    amount: 1500000,
  },
  {
    id: "sc3",
    title: "Akıllı Geri Dönüşüm Sistemleri",
    companyName: "EcoTech Sistemleri",
    logo: "/placeholder.svg",
    amount: 1000000,
  },
  {
    id: "sc4",
    title: "Yapay Zeka Destekli Sağlık Asistanı",
    companyName: "HealthAI Corp.",
    logo: "/placeholder.svg",
    amount: 2500000,
  },
  {
    id: "sc5",
    title: "Biyoplastik Üretim Tesisi",
    companyName: "GreenPlast A.Ş.",
    logo: "/placeholder.svg",
    amount: 1800000,
  },
  {
    id: "sc6",
    title: "Akıllı Tarım Teknolojileri",
    companyName: "AgriTech Solutions",
    logo: "/placeholder.svg",
    amount: 1200000,
  },
  {
    id: "sc7",
    title: "Yenilenebilir Enerji Depolama Çözümleri",
    companyName: "EnerStore Inc.",
    logo: "/placeholder.svg",
    amount: 3000000,
  },
  {
    id: "sc8",
    title: "Dijital Eğitim Platformu",
    companyName: "EduTech Innovations",
    logo: "/placeholder.svg",
    amount: 1700000,
  },
  {
    id: "sc9",
    title: "Akıllı Ev Otomasyon Sistemleri",
    companyName: "SmartHome Co.",
    logo: "/placeholder.svg",
    amount: 900000,
  },
  {
    id: "sc10",
    title: "Biyomedikal Cihaz Geliştirme",
    companyName: "MedDevice Labs",
    logo: "/placeholder.svg",
    amount: 2200000,
  },
  {
    id: "sc11",
    title: "Sürdürülebilir Ambalaj Çözümleri",
    companyName: "EcoPack Industries",
    logo: "/placeholder.svg",
    amount: 1300000,
  },
  {
    id: "sc12",
    title: "Yapay Zeka Destekli Finans Analizi",
    companyName: "FinAI Technologies",
    logo: "/placeholder.svg",
    amount: 1900000,
  },
  {
    id: "1",
    title: "Proje A",
    logo: "/placeholder.svg",
    amount: 1000000,
  },
  {
    id: "2",
    title: "Proje B",
    logo: "/placeholder.svg",
    amount: 750000,
  },
  {
    id: "3",
    title: "Proje C",
    logo: "/placeholder.svg",
    amount: 500000,
  },
  {
    id: "4",
    title: "Proje D",
    logo: "/placeholder.svg",
    amount: 250000,
  },
  {
    id: "5",
    title: "Proje E",
    logo: "/placeholder.svg",
    amount: 100000,
  },
  {
    id: "6",
    title: "Proje F",
    logo: "/placeholder.svg",
    amount: 50000,
  },
]

